export const EVENT_NAMES = {
  MEMBER_EXISTS_BY_ID: 'MEMBER_EXISTS_BY_ID',
  MEMBERSHIP_CREATED: 'MEMBERSHIP_CREATED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  GET_MEMBER_MEMBERSHIPS: 'GET_MEMBER_MEMBERSHIPS',
  GET_MEMBER_PAYMENTS: 'GET_MEMBER_PAYMENTS',
  GET_MEMBERSHIP_BY_ID: 'GET_MEMBERSHIP_BY_ID',
  GET_PLAN_BY_ID: 'GET_PLAN_BY_ID',
  GET_MEMBER_BY_ID: 'GET_MEMBER_BY_ID',
} as const;
